// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYZCR_MjCW_gLLM7aieK7T4NTgX9XLHNo',
    appId: '1:859051913082:android:2171e4b2dc9bb24dc630c3',
    messagingSenderId: '859051913082',
    projectId: 'studuler',
    storageBucket: 'studuler.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYHwBg4pDNhs0SDX0fiJVAC4Boo4lxKDQ',
    appId: '1:859051913082:ios:d2342b348009183fc630c3',
    messagingSenderId: '859051913082',
    projectId: 'studuler',
    storageBucket: 'studuler.firebasestorage.app',
    androidClientId: '859051913082-2bjuva3udj4tti2jg8a59fuu4s1ent63.apps.googleusercontent.com',
    iosClientId: '859051913082-24nkdjnbhjohaa76obvmrp0i0a1v2o2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.studuler',
  );

}